### ISSUE TITLE
emerald 0.8.12 often terminated unexpectedly, especially when press ALT + TAB to switch window.

### ISSUE THREAD

**Issue by moontide** [compiz-reloaded/emerald#1]
After upgraded `compiz`\* and `emerald` package to 0.8.12 in Fedora 23, I often encountered "window title bar been lost" issue. After several days, I realized that it's emerald been terminated.

I can't reproduce this issue each time, but mostly it often occurred after press ALT + TAB (to switch window).

I must restart compiz or reenable "Window Decoration" in "CompizConfig Setting Manager" to take window title back.

I can only find audit logs in `/var/log/messages`. Although it is audit log, but I guess each line means I restarted compiz or reenabled "Window Decorator".

```
# grep -n emerald messages
725:Feb 21 11:41:07 liuyan-tx300 audit: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=1 pid=5911 comm="emerald" exe="/usr/bin/emerald" sig=6
726:Feb 21 11:44:45 liuyan-tx300 audit: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=1 pid=14307 comm="emerald" exe="/usr/bin/emerald" sig=6
734:Feb 21 11:51:47 liuyan-tx300 audit: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=1 pid=14619 comm="emerald" exe="/usr/bin/emerald" sig=6
757:Feb 21 11:57:35 liuyan-tx300 audit: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=1 pid=14852 comm="emerald" exe="/usr/bin/emerald" sig=6
892:Feb 21 13:43:41 liuyan-tx300 audit: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=1 pid=15789 comm="emerald" exe="/usr/bin/emerald" sig=6
1156:Feb 21 16:35:07 liuyan-tx300 audit: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=1 pid=21168 comm="emerald" exe="/usr/bin/emerald" sig=6
1378:Feb 21 20:03:06 liuyan-tx300 audit: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=1 pid=3980 comm="emerald" exe="/usr/bin/emerald" sig=6
1379:Feb 21 20:03:42 liuyan-tx300 audit: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=1 pid=677 comm="emerald" exe="/usr/bin/emerald" sig=6
1401:Feb 21 20:13:35 liuyan-tx300 audit: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=1 pid=861 comm="emerald" exe="/usr/bin/emerald" sig=6
1418:Feb 21 20:18:33 liuyan-tx300 audit: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=1 pid=4930 comm="emerald" exe="/usr/bin/emerald" sig=6
1423:Feb 21 20:22:02 liuyan-tx300 audit: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=1 pid=5709 comm="emerald" exe="/usr/bin/emerald" sig=6
```

**Comment by raveit65** [comment]
Thanks for reportings this, and we could reporoduce it if using the static-application-switcher.
You should see something like this in ~.xsession-errors
```
emerald: cairo-surface.c:953: cairo_surface_destroy: Zusicherung Â»((*&(&surface->ref_count)->ref_count) > 0)Â« nicht erfÃŒllt.
```
Can you please provide the content of ~.config/compiz/compizconfig/Default.ini ?
I guess downgrading only emerald to previous version helps.
Do you see this problem with gtk-decorator?

**Comment by raveit65** [comment]
@moontide 
I've updated the fedora bodhi 0.8.12 update. Please test and leave karma

**Comment by moontide** [comment]
@raveit65 , After one hour testing. this issue isn't reproduced. emerald-0.8.12-2.fc23 fixed this issue. Thanks!

**Comment by kn00tcn** [comment]
i dont think this ever fixed for me in mate, random emerald disappearances for months

recently tried in xfce for a bit, but havent seen crashes

**Comment by ethus3h** [comment]
Not sure about the alt+tab correlation, but I certainly do see the emerald decorations disappear fairly often. I don't remember if I've gotten it in gdb yet though...

**Comment by XRevan86** [comment]
@kn00tcn, @ethus3h, if you have cairo 1.15.3 or older, make sure Emerald is built with Gtk2. And do tell :-).

**Comment by ethus3h** [comment]
I have cairo 1.14.6, but emerald is built with Gtk2 (the gtk3 USE flag is not set).

**Comment by ethus3h** [comment]
Tasty backtrace of emerald crash. It's warm and crunchy, hot off the debugger! http://futuramerlin.com/issue-tracker/file_download.php?file_id=48&type=bug

**Comment by XRevan86** [comment]
It's been months yet I still can't make sense of it…
@ethus3h, still no idea how to reproduce it?

**Comment by ethus3h** [comment]
Sadly, no, not beyond using Compiz/Emerald for a while until it happens.x

**Comment by XRevan86** [comment]
@ethus3h, by the way, what Emerald theme do you use?

**Comment by ethus3h** [comment]
This one: https://github.com/ethus3h/wreathe/tree/master/usr/share/emerald/themes/Wreathe%207.3%20HiDPI

**Comment by kn00tcn** [comment]
i was on a very slightly modified rezlooks-graphite

**Comment by XRevan86** [comment]
I was running Emerald with the Wreathe (non-HiDPI) theme for several days yet nothing happened…

**Comment by ethus3h** [comment]
Huh, interesting. Do you use the Static App Switcher regularly?

**Comment by XRevan86** [comment]
@ethus3h, no, I use the "Application Switcher".

**Comment by ethus3h** [comment]
I'll try using that one for a bit and see if I notice the issue.

**Comment by ethus3h** [comment]
Ugh, how do you use this? It's unbelievably laggy for me...

**Comment by ethus3h** [comment]
Ok, so what happens is, when I'm using the Static Application Switcher, the popup will appear, and get a thick white border around it that usually does not appear. Shortly thereafter, Emerald will die. Maybe Emerald is erroneously trying to decorate the Static Application Switcher popup?

**Comment by kn00tcn** [comment]
what do you mean laggy? static sure looks similar to regular, both are doing a fade animation, are you actually seeing poor fps even though the regular switcher should be more demanding?

the supposed vsync is still garbage just like xfce's supposed vsync, i'm only testing compiz right now after compton or something x related froze during the locking process (never had that happen, but audacity did break x earlier in the day, ended up killing compton in a tty)

i havent used compiz in several months, now i'm seeing blocky texture artifacts during the fade to add to the bugs (i assume nouveau changed or my curent session is quite broken after all the killing)

how do i find out the gtk versions in use? the actual package versions are whatever f25 has, cairo 1.14.8, emerald 0.8.12.4, compiz 0.8.12.3 (why is this not .4)

not sure if this is my crash, there's no time in xsession-errors `*** Error in `emerald': corrupted double-linked list (not small)`

what i find interesting is that emerald wont crash after the first time for me, until the session starts all over or maybe a long idle period

**Comment by ethus3h** [comment]
When I say laggy I don't mean FPS-wise — rather, the design of the plugin (confusing highlighting and animations) makes it really distracting, confusing, frustrating, and just generally hard for me to use. This makes it feel *muuuuch* slower and in-my-face than staticswitcher, which feels snappy and I don't really even notice I'm using it. This is just a matter of my personal preference, but it is sufficiently disruptive to my workflow that I can't really test it for any length of time, because after about 10 minutes of using the computer with the non-static switcher turned on, I instinctively start using Scale or clicking the taskbar instead.

**Comment by kn00tcn** [comment]
oh right, the switcher is in the way, reminds me of when people first started using jquery lightboxes, i'd sit there irritated watching the screen slowly darken, slowly enlarge a white rectangle, then finally fade in the image instead of doing all animations at the same time while staying within 100ms

you can tweak the speed of both of these switchers, no need to settle for defaults

(clicking the taskbar is the fastest anyway if it's not going to the previously used window, this is one reason why gnome3 is terrible for not having a window list on the main panel)

**Comment by ethus3h** [comment]
my static switcher config is so that there is *no* animation or popup unless I take more than like a quarter second before releasing the keyboard config, with the result that the vast majority of the times I use it, I never see any animation or popup at all. I don't think there's any way to do that with the non-static one...

**Comment by XRevan86** [comment]
Yes, the static switcher definitely crashes Emerald.

**Comment by kn00tcn** [comment]
both switchers

**Comment by ethus3h** [comment]
For what it's worth, when I switch windows, I'm seeing a border and shadow drawn around the switcher very briefly, and then once the switcher stabilizes into the next state after switching the border goes away. I hadn't noticed it before because it was happening too fast, but I happened to be running Emerald under valgrind with the system under very heavy CPU load, and it made it slow down enough for me to notice it. I'm not sure if this is related, but it seems to be a thing.

In other news, I'm seeing [a lot of what I think are use-after-frees in the valgrind output](https://gist.github.com/ethus3h/5eb618cc51d99d54fe27796cb14789ff) (I'm new to valgrind, so I'm not really familiar with reading the output yet.)

I haven't reproduced this crash yet under valgrind, though.

**Comment by kn00tcn** [comment]
guess i havent seen emerald crash since the patch, nice
